### ISSUE TITLE
curl error on key for repo that is not enabled

### ISSUE THREAD

**Issue by xsuchy** [svarshavchik/clean-rpm-gpg-pubkey#4]
I have repo file that uses

  /etc/yum.repos.d/c8s-epel.repo:gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8

but this repository hase

enabled=0

but when I run the script I got:

```
$ sudo /usr/bin/clean-rpm-gpg-pubkey
curl: (37) Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
Could not execute curl
```

This is Fedora 41.

**Comment by svarshavchik** [comment]
The alternative is that disabling a repo will end up with its pgp key getting uninstalled, which will be even worse.

This looks like a packaging error, a repository package installing a repository but not its pgp key.

**Comment by teohhanhui** [comment]
> The alternative is that disabling a repo will end up with its pgp key getting uninstalled, which will be even worse.

Isn't the bug that the script is failing with the curl error instead of just ignoring disabled repos?
